### ISSUE TITLE
www.jselement.org has been decomissioned

### ISSUE THREAD

**Issue by dragonworx** [dragonworx/jsel#3]
Due to lack of interest in maintenance costs, the site has been decomissioned and is no longer available.

However you can get the source code from https://github.com/dragonworx/jselementorg and run it locally (file:// protocol fine). This gives you the same functionality, on your own machine.

**Comment by richardneililagan** [comment]
Hey Ali,

If not on a dedicated domain, you might want to consider hosting the original landing site on a Github project page instead.

Probably doesn't have as much charm as www.jselement.org, but dragonwork.github.io/jsel is still descriptive, and it's awesome hosting space for project page landings. :)

**Comment by dragonworx** [comment]
Hey Richard, how are you man?Thanks for the tip, yes a hosted page would be much better, I did make the source available on github from the original site - dragonworx/jselementorg - but i haven't updated the readme in the main repo :(
|   |
|   |  |   |   |   |   |   |
| dragonworx/jselementorgjselementorg - The interactive tools from www.jselement.org as a stand alone local site |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |

I hope I didn't piss off too many users, it's pretty bad to just cut something out. I shut down that server but been too busy to tidy up after. Will give it a go cheers!Ali 


     On Sunday, 12 July 2015, 18:47, Richard Neil Ilagan <notifications@github.com> wrote:
   

 Hey Ali,If not on a dedicated domain, you might want to consider hosting the original landing site on a Github project page instead.Probably doesn't have as much charm as www.jselement.org, but dragonwork.github.io/jsel is still descriptive, and it's awesome hosting space for project page landings. :)—

**Comment by richardneililagan** [comment]
Yeah, it's a bit of a shame, man. This is awesome work!

Going GH pages also gives you an excuse to check out Jekyll, if ever that interests you. Haha!

Good luck!

**Comment by dragonworx** [comment]
Hey thanks again Richard, I've created a project page to host the old site and have republished on npm to 1.1.4.jselement.org - Interactive Editor

|   |
|   |   |   |   |   |
| jselement.org - Interactive EditorXPath Examples Select One Select All Input Format Source Schema Mappings Examples Simple Basic  |
|  |
| View on dragonworx.github.io | Preview by Yahoo |
|  |
|   |

Cheers!Ali 


     On Tuesday, 14 July 2015, 11:35, Richard Neil Ilagan <notifications@github.com> wrote:
   

 Yeah, it's a bit of a shame, man. This is awesome work!Going GH pages also gives you an excuse to check out Jekyll, if ever that interests you. Haha!Good luck!—
