### ISSUE TITLE
License is unclear, CC/SA or MIT?

### ISSUE THREAD

**Issue by asford** [dragonworx/jsel#4]
`jsel` is a great tool, however I'm a little unclear as to the current license. The package.json states that it's  under MIT, however the source appears state that it it's under CC-SA. This is an issue for integration with many liberally licensed projects, as CC-SA is essentially a copyleft license. @dragonworx, can you clarify the license?

**Comment by dragonworx** [comment]
Hi, `jsel` is a modification of the `xpath` npm module which originally had an MIT licence. I decided to follow the same licence type for `jsel`, so definitely MIT.
