### ISSUE TITLE
Add a command line interface

### ISSUE THREAD

**Issue by talwrii** [dragonworx/jsel#8]
See for example:  https://github.com/talwrii/jselcli

See [jq](https://stedolan.github.io/jq/) to understand why this is important.

**Comment by dragonworx** [comment]
Hey @talwrii this is great! I see you have taken care of this 👍 
I can't find the package on npm, are you planning on publishing?
I guess I can mark this as closed right?

**Comment by talwrii** [comment]
> I can't find the package on npm, are you planning on publishing?

I didn't want to create competition or redundancy if you wanted to merge this into `jsel` or maintain this yourself.

> I guess I can mark this as closed right?

So there's a question of ownership / merging.

* Would you like this in `jsel` itself? (I'm happy to create a pull request)
* If not, would you like to be the owner of  `jselcli` on npm?
* If not, are you happy for me to use the name `jselcli` and be the maintainer on npm?

**Comment by dragonworx** [comment]
> are you happy for me to use the name jselcli and be the maintainer on npm?

I think that would be great, perhaps name the module `jsel-cli`? Thats a standard pattern for having variants of a package, like `react-xyz` etc.. 

I think it would work well having the core functionality in one module and the cli in another.

Thanks for the great idea, looking forward to seeing it published.

I propose closing this once you've published, just update here when ready.

**Comment by talwrii** [comment]
> I think that would be great, perhaps name the module jsel-cli?

Sounds good.

**Comment by dragonworx** [comment]
Going to close issue, @talwrii can publish package when ready.
